### ISSUE TITLE
The icd11 (MMS) alias is defined twice

### ISSUE THREAD

**Issue by lawley** [hl7-eu/dgc#1]
Second definition is here:

https://github.com/hl7-eu/dgc/blob/33e274f92725fd3e7202b0006d14e1e1460115b5/input/fsh/Alias.fsh#L11

**Comment by gcangioli** [comment]
I know .. a lot of cleaning up is needed :-) 
Thanks for pointing out

**Comment by danka74** [comment]
See https://github.com/hl7-eu/dgc/commit/de0f8528d49612bf86baaca8eeb117b053bc9921
