### ISSUE TITLE
Duplicate codes in ICD11 vaccine reference set

### ISSUE THREAD

**Issue by lawley** [hl7-eu/dgc#3]
https://github.com/hl7-eu/dgc/blob/33e274f92725fd3e7202b0006d14e1e1460115b5/input/fsh/terminologies.fsh#L19

See above.  Every code is included multiple times.

**Comment by gcangioli** [comment]
Thanks, Fixed with the last (0b4127de2c912fc49dbfde1f95bec77e0886e9f2) commit
