### ISSUE TITLE
SPOR URI

### ISSUE THREAD

**Issue by danka74** [hl7-eu/dgc#5]
The SPOR URI https://spor.ema.europa.eu/omswi/#/ does not work too well. Will ask SPOR about this...

**Comment by chgessner** [comment]
I will attend the regular meeting of the EMA IOS SPOR Task Force on Monday 12th April. If you want me to bring forward something specific there, please let me know.

**Comment by danka74** [comment]
Thanks @chgessner , I have sent an email to Panagiotis about this today. In the mean time, I've changed the VS to use the OID.

**Comment by danka74** [comment]
Reply from SPOR:

We use FHIR for the Product Management System and the Substance Management System in SPOR.

For Product data we have a few data elements which are references to OMS entities. We reference the Location level, therefore use identifiers with a pattern of LOC-XXX. The system value we decided to use is the OMS REST API endpoint for Locations. A similar approach can be used to reference Organisations as well. Please see below examples for refencing a Manufacturer, a Marketing Authorisation Holder and a Regulator:

On MedicinalProductDefinition resource type
```
<manufacturer>
<identifier>
<system value="https://spor.ema.europa.eu/v1/locations"/>
<value value="LOC-XXX"/>
</identifier>
</manufacturer>
```

On RegulatedAuthorization resource type
```
<holder>
<identifier>
<system value="https://spor.ema.europa.eu/v1/locations"/>
<value value="LOC-YYY"/>
</identifier>
</holder>
<regulator>
<identifier>
<system value="https://spor.ema.europa.eu/v1/locations"/>
<value value="LOC-ZZZ"/>
</identifier>
</regulator>

```
To reference an Organisation the respective identifier would use the Organisations REST Endpoint from OMS:

```
<identifier>
<system value="https://spor.ema.europa.eu/v1/organisations"/>
<value value="ORG-XXX"/>
</identifier>
```


The manufacturer, holder and regulator attributes are of type Reference (http://hl7.org/fhir/references.html#Reference) which includes an identifier element of type Identifier (http://hl7.org/fhir/datatypes.html#Identifier). Please see http://hl7.org/fhir/datatypes.html for extra information on data types in FHIR as well.


Please let me know if you’d like more information or have further questions.

**Comment by danka74** [comment]
So, the SPOR URI is solved, now I'm frankly worried about the Vaccine medicinal product URI: https://ec.europa.eu/health/documents/community-register/html/ looks like the URL for their web pages ("documents" and "html" in the URI looks suspicious) which might change of they update their Content Management System.

**Comment by costateixeira** [comment]
Hi. I'd like to understand this - where is this URI used? I think your worry @danka74 is very legitimate

**Comment by danka74** [comment]
@costateixeira , see https://github.com/hl7-eu/dgc/blob/1c7478605630b32902f0fcde19bae2b436dddb75/input/fsh/terminologies_eu.fsh#L39
The URI is used to identify the code system where the vaccine product codes are provided. 

Edit: So, the current URI in the Alias file is just a placeholder until clarity has been reached! The URI in the eHN Subgroup on Semantics document is still "https://ec.europa.eu/health/documents/community-register/html/"

**Comment by costateixeira** [comment]
ok thanks I was missing that last clarification. Having a system URL pointing to a ...document/community-register/html seems indeed strange.

**Comment by danka74** [comment]
I have some changes in my local repo I haven't committed yet. Perhaps it's time, although there are issues.

**Comment by danka74** [comment]
Just committed the change of URI (which I suspect is wrong!). Further, the registration is not done by EMA but by the EC, so the alias name is not the best.

**Comment by costateixeira** [comment]
Perhaps a separate issue should be created for that. Agree the URI doesn't see appropriate for the use
